FROM python:3.12-slim AS builder
WORKDIR /app
COPY services/analyzer/requirements.txt .
RUN pip install --default-timeout=100 --no-cache-dir -r requirements.txt
COPY services/analyzer/ ./

EXPOSE 8000
CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
