"""Tests for the evidence-backed suggestedFix (auto-PR remediation doc)."""
import unittest

from app.ml.causal import generate_ai_diagnosis


class TestSuggestedFix(unittest.TestCase):

    def test_generates_evidence_backed_fix_with_log_evidence(self):
        diag = generate_ai_diagnosis(
            ranked_causes=[
                {"cause": "latency", "score": 0.92, "lag": 2},
                {"cause": "cpu_usage", "score": 0.61, "lag": 1},
            ],
            service_id="payment-api",
            log_evidence={
                "exceptionTypes": [{"type": "java.sql.SQLTimeoutException", "count": 14}],
                "errorKeywords": [{"keyword": "timeout", "count": 30}],
                "http5xx": 42,
                "sampleLines": ["2026-01-01 ERROR db pool exhausted"],
            },
        )
        fix = diag["suggestedFix"]
        self.assertIsNotNone(fix)
        self.assertEqual(fix["targetFile"], "astrawatch-remediation.md")
        # The remediation doc must contain the real evidence facts.
        self.assertIn("payment-api", fix["patch"])
        self.assertIn("SQLTimeoutException", fix["patch"])
        self.assertIn("HTTP 5xx: 42", fix["patch"])  # real http5xx evidence
        self.assertIn("42", fix["patch"])
        self.assertIn("timeout", fix["patch"])
        self.assertIn("Ranked root causes", fix["patch"])
        self.assertIn("latency", fix["patch"])

    def test_generates_fix_even_without_log_evidence(self):
        diag = generate_ai_diagnosis(
            ranked_causes=[{"cause": "memory_usage", "score": 0.8, "lag": 1}],
            service_id="worker",
        )
        fix = diag["suggestedFix"]
        self.assertIsNotNone(fix)
        self.assertIn("worker", fix["patch"])
        self.assertIn("memory_usage", fix["patch"])
        self.assertIn("Generated by AstraWatch", fix["patch"])

    def test_fix_never_contains_fabricated_code_diff(self):
        # Even with no causes/evidence, the doc must be evidence-statement-only
        # and must not claim a code change was made.
        diag = generate_ai_diagnosis(ranked_causes=[], service_id="unknown")
        fix = diag["suggestedFix"]
        self.assertIsNotNone(fix)
        patch = fix["patch"].lower()
        self.assertNotIn("```diff", patch)
        self.assertNotIn("+ pool.setmaxsize", patch)


if __name__ == "__main__":
    unittest.main()
