global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'astrawatch-collector'
    static_configs:
      - targets: ['collector:8080']
  - job_name: 'astrawatch-operator'
    static_configs:
      - targets: ['operator:8081']
