// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: internal/ingest/agentproto/agent.proto

package agentproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentIngest_StreamMetrics_FullMethodName   = "/astrawatch.agent.v1.AgentIngest/StreamMetrics"
	AgentIngest_SendMetricBatch_FullMethodName = "/astrawatch.agent.v1.AgentIngest/SendMetricBatch"
	AgentIngest_HealthCheck_FullMethodName     = "/astrawatch.agent.v1.AgentIngest/HealthCheck"
)

// AgentIngestClient is the client API for AgentIngest service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentIngestClient interface {
	// Agent streams metric batches to the Collector
	StreamMetrics(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[MetricBatch, IngestResponse], error)
	// Agent sends a single batch (for backlog replay)
	SendMetricBatch(ctx context.Context, in *MetricBatch, opts ...grpc.CallOption) (*IngestResponse, error)
	// Health check
	HealthCheck(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type agentIngestClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentIngestClient(cc grpc.ClientConnInterface) AgentIngestClient {
	return &agentIngestClient{cc}
}

func (c *agentIngestClient) StreamMetrics(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[MetricBatch, IngestResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentIngest_ServiceDesc.Streams[0], AgentIngest_StreamMetrics_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[MetricBatch, IngestResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentIngest_StreamMetricsClient = grpc.ClientStreamingClient[MetricBatch, IngestResponse]

func (c *agentIngestClient) SendMetricBatch(ctx context.Context, in *MetricBatch, opts ...grpc.CallOption) (*IngestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IngestResponse)
	err := c.cc.Invoke(ctx, AgentIngest_SendMetricBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentIngestClient) HealthCheck(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, AgentIngest_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentIngestServer is the server API for AgentIngest service.
// All implementations must embed UnimplementedAgentIngestServer
// for forward compatibility.
type AgentIngestServer interface {
	// Agent streams metric batches to the Collector
	StreamMetrics(grpc.ClientStreamingServer[MetricBatch, IngestResponse]) error
	// Agent sends a single batch (for backlog replay)
	SendMetricBatch(context.Context, *MetricBatch) (*IngestResponse, error)
	// Health check
	HealthCheck(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedAgentIngestServer()
}

// UnimplementedAgentIngestServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentIngestServer struct{}

func (UnimplementedAgentIngestServer) StreamMetrics(grpc.ClientStreamingServer[MetricBatch, IngestResponse]) error {
	return status.Error(codes.Unimplemented, "method StreamMetrics not implemented")
}
func (UnimplementedAgentIngestServer) SendMetricBatch(context.Context, *MetricBatch) (*IngestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendMetricBatch not implemented")
}
func (UnimplementedAgentIngestServer) HealthCheck(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedAgentIngestServer) mustEmbedUnimplementedAgentIngestServer() {}
func (UnimplementedAgentIngestServer) testEmbeddedByValue()                     {}

// UnsafeAgentIngestServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentIngestServer will
// result in compilation errors.
type UnsafeAgentIngestServer interface {
	mustEmbedUnimplementedAgentIngestServer()
}

func RegisterAgentIngestServer(s grpc.ServiceRegistrar, srv AgentIngestServer) {
	// If the following call panics, it indicates UnimplementedAgentIngestServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentIngest_ServiceDesc, srv)
}

func _AgentIngest_StreamMetrics_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentIngestServer).StreamMetrics(&grpc.GenericServerStream[MetricBatch, IngestResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentIngest_StreamMetricsServer = grpc.ClientStreamingServer[MetricBatch, IngestResponse]

func _AgentIngest_SendMetricBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetricBatch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentIngestServer).SendMetricBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentIngest_SendMetricBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentIngestServer).SendMetricBatch(ctx, req.(*MetricBatch))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentIngest_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentIngestServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentIngest_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentIngestServer).HealthCheck(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentIngest_ServiceDesc is the grpc.ServiceDesc for AgentIngest service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentIngest_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "astrawatch.agent.v1.AgentIngest",
	HandlerType: (*AgentIngestServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMetricBatch",
			Handler:    _AgentIngest_SendMetricBatch_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _AgentIngest_HealthCheck_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamMetrics",
			Handler:       _AgentIngest_StreamMetrics_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "internal/ingest/agentproto/agent.proto",
}
