// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: internal/ingest/agentproto/agent.proto

package agentproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MetricPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         float64                `protobuf:"fixed64,2,opt,name=value,proto3" json:"value,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricPoint) Reset() {
	*x = MetricPoint{}
	mi := &file_internal_ingest_agentproto_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricPoint) ProtoMessage() {}

func (x *MetricPoint) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ingest_agentproto_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricPoint.ProtoReflect.Descriptor instead.
func (*MetricPoint) Descriptor() ([]byte, []int) {
	return file_internal_ingest_agentproto_agent_proto_rawDescGZIP(), []int{0}
}

func (x *MetricPoint) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MetricPoint) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *MetricPoint) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *MetricPoint) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type MetricBatch struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	AgentId             string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Hostname            string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Cluster             string                 `protobuf:"bytes,3,opt,name=cluster,proto3" json:"cluster,omitempty"`
	Metrics             []*MetricPoint         `protobuf:"bytes,4,rep,name=metrics,proto3" json:"metrics,omitempty"`
	BatchSeq            int64                  `protobuf:"varint,5,opt,name=batch_seq,json=batchSeq,proto3" json:"batch_seq,omitempty"`                                    // monotonic sequence for dedup
	OriginalTimestampMs int64                  `protobuf:"varint,6,opt,name=original_timestamp_ms,json=originalTimestampMs,proto3" json:"original_timestamp_ms,omitempty"` // when the batch was created (not when replayed)
	IsBacklog           bool                   `protobuf:"varint,7,opt,name=is_backlog,json=isBacklog,proto3" json:"is_backlog,omitempty"`                                 // true if this is a replayed backlog batch
	QueueDepth          int64                  `protobuf:"varint,8,opt,name=queue_depth,json=queueDepth,proto3" json:"queue_depth,omitempty"`                              // remaining entries in local buffer
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *MetricBatch) Reset() {
	*x = MetricBatch{}
	mi := &file_internal_ingest_agentproto_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricBatch) ProtoMessage() {}

func (x *MetricBatch) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ingest_agentproto_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricBatch.ProtoReflect.Descriptor instead.
func (*MetricBatch) Descriptor() ([]byte, []int) {
	return file_internal_ingest_agentproto_agent_proto_rawDescGZIP(), []int{1}
}

func (x *MetricBatch) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *MetricBatch) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *MetricBatch) GetCluster() string {
	if x != nil {
		return x.Cluster
	}
	return ""
}

func (x *MetricBatch) GetMetrics() []*MetricPoint {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *MetricBatch) GetBatchSeq() int64 {
	if x != nil {
		return x.BatchSeq
	}
	return 0
}

func (x *MetricBatch) GetOriginalTimestampMs() int64 {
	if x != nil {
		return x.OriginalTimestampMs
	}
	return 0
}

func (x *MetricBatch) GetIsBacklog() bool {
	if x != nil {
		return x.IsBacklog
	}
	return false
}

func (x *MetricBatch) GetQueueDepth() int64 {
	if x != nil {
		return x.QueueDepth
	}
	return 0
}

type IngestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      int32                  `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Rejected      int32                  `protobuf:"varint,2,opt,name=rejected,proto3" json:"rejected,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestResponse) Reset() {
	*x = IngestResponse{}
	mi := &file_internal_ingest_agentproto_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestResponse) ProtoMessage() {}

func (x *IngestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ingest_agentproto_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestResponse.ProtoReflect.Descriptor instead.
func (*IngestResponse) Descriptor() ([]byte, []int) {
	return file_internal_ingest_agentproto_agent_proto_rawDescGZIP(), []int{2}
}

func (x *IngestResponse) GetAccepted() int32 {
	if x != nil {
		return x.Accepted
	}
	return 0
}

func (x *IngestResponse) GetRejected() int32 {
	if x != nil {
		return x.Rejected
	}
	return 0
}

func (x *IngestResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_internal_ingest_agentproto_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ingest_agentproto_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_internal_ingest_agentproto_agent_proto_rawDescGZIP(), []int{3}
}

func (x *HealthRequest) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"` // HEALTHY, DEGRADED, DOWN
	UptimeSeconds int64                  `protobuf:"varint,2,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	BacklogSize   int64                  `protobuf:"varint,3,opt,name=backlog_size,json=backlogSize,proto3" json:"backlog_size,omitempty"`
	QueueDepth    int64                  `protobuf:"varint,4,opt,name=queue_depth,json=queueDepth,proto3" json:"queue_depth,omitempty"`
	ActiveProbes  []string               `protobuf:"bytes,5,rep,name=active_probes,json=activeProbes,proto3" json:"active_probes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_internal_ingest_agentproto_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ingest_agentproto_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_internal_ingest_agentproto_agent_proto_rawDescGZIP(), []int{4}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *HealthResponse) GetBacklogSize() int64 {
	if x != nil {
		return x.BacklogSize
	}
	return 0
}

func (x *HealthResponse) GetQueueDepth() int64 {
	if x != nil {
		return x.QueueDepth
	}
	return 0
}

func (x *HealthResponse) GetActiveProbes() []string {
	if x != nil {
		return x.ActiveProbes
	}
	return nil
}

type AgentIdentity struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AgentId         string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	Hostname        string                 `protobuf:"bytes,2,opt,name=hostname,proto3" json:"hostname,omitempty"`
	KernelVersion   string                 `protobuf:"bytes,3,opt,name=kernel_version,json=kernelVersion,proto3" json:"kernel_version,omitempty"`
	AgentVersion    string                 `protobuf:"bytes,4,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	SupportedProbes []string               `protobuf:"bytes,5,rep,name=supported_probes,json=supportedProbes,proto3" json:"supported_probes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AgentIdentity) Reset() {
	*x = AgentIdentity{}
	mi := &file_internal_ingest_agentproto_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentIdentity) ProtoMessage() {}

func (x *AgentIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_internal_ingest_agentproto_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentIdentity.ProtoReflect.Descriptor instead.
func (*AgentIdentity) Descriptor() ([]byte, []int) {
	return file_internal_ingest_agentproto_agent_proto_rawDescGZIP(), []int{5}
}

func (x *AgentIdentity) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *AgentIdentity) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *AgentIdentity) GetKernelVersion() string {
	if x != nil {
		return x.KernelVersion
	}
	return ""
}

func (x *AgentIdentity) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *AgentIdentity) GetSupportedProbes() []string {
	if x != nil {
		return x.SupportedProbes
	}
	return nil
}

var File_internal_ingest_agentproto_agent_proto protoreflect.FileDescriptor

const file_internal_ingest_agentproto_agent_proto_rawDesc = "" +
	"\n" +
	"&internal/ingest/agentproto/agent.proto\x12\x13astrawatch.agent.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf2\x01\n" +
	"\vMetricPoint\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value\x128\n" +
	"\ttimestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12D\n" +
	"\x06labels\x18\x04 \x03(\v2,.astrawatch.agent.v1.MetricPoint.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xab\x02\n" +
	"\vMetricBatch\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12\x18\n" +
	"\acluster\x18\x03 \x01(\tR\acluster\x12:\n" +
	"\ametrics\x18\x04 \x03(\v2 .astrawatch.agent.v1.MetricPointR\ametrics\x12\x1b\n" +
	"\tbatch_seq\x18\x05 \x01(\x03R\bbatchSeq\x122\n" +
	"\x15original_timestamp_ms\x18\x06 \x01(\x03R\x13originalTimestampMs\x12\x1d\n" +
	"\n" +
	"is_backlog\x18\a \x01(\bR\tisBacklog\x12\x1f\n" +
	"\vqueue_depth\x18\b \x01(\x03R\n" +
	"queueDepth\"^\n" +
	"\x0eIngestResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\x05R\baccepted\x12\x1a\n" +
	"\brejected\x18\x02 \x01(\x05R\brejected\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"*\n" +
	"\rHealthRequest\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\"\xb8\x01\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12%\n" +
	"\x0euptime_seconds\x18\x02 \x01(\x03R\ruptimeSeconds\x12!\n" +
	"\fbacklog_size\x18\x03 \x01(\x03R\vbacklogSize\x12\x1f\n" +
	"\vqueue_depth\x18\x04 \x01(\x03R\n" +
	"queueDepth\x12#\n" +
	"\ractive_probes\x18\x05 \x03(\tR\factiveProbes\"\xbd\x01\n" +
	"\rAgentIdentity\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1a\n" +
	"\bhostname\x18\x02 \x01(\tR\bhostname\x12%\n" +
	"\x0ekernel_version\x18\x03 \x01(\tR\rkernelVersion\x12#\n" +
	"\ragent_version\x18\x04 \x01(\tR\fagentVersion\x12)\n" +
	"\x10supported_probes\x18\x05 \x03(\tR\x0fsupportedProbes2\x99\x02\n" +
	"\vAgentIngest\x12X\n" +
	"\rStreamMetrics\x12 .astrawatch.agent.v1.MetricBatch\x1a#.astrawatch.agent.v1.IngestResponse(\x01\x12X\n" +
	"\x0fSendMetricBatch\x12 .astrawatch.agent.v1.MetricBatch\x1a#.astrawatch.agent.v1.IngestResponse\x12V\n" +
	"\vHealthCheck\x12\".astrawatch.agent.v1.HealthRequest\x1a#.astrawatch.agent.v1.HealthResponseB\x1eZ\x1c./internal/ingest/agentprotob\x06proto3"

var (
	file_internal_ingest_agentproto_agent_proto_rawDescOnce sync.Once
	file_internal_ingest_agentproto_agent_proto_rawDescData []byte
)

func file_internal_ingest_agentproto_agent_proto_rawDescGZIP() []byte {
	file_internal_ingest_agentproto_agent_proto_rawDescOnce.Do(func() {
		file_internal_ingest_agentproto_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_ingest_agentproto_agent_proto_rawDesc), len(file_internal_ingest_agentproto_agent_proto_rawDesc)))
	})
	return file_internal_ingest_agentproto_agent_proto_rawDescData
}

var file_internal_ingest_agentproto_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_internal_ingest_agentproto_agent_proto_goTypes = []any{
	(*MetricPoint)(nil),           // 0: astrawatch.agent.v1.MetricPoint
	(*MetricBatch)(nil),           // 1: astrawatch.agent.v1.MetricBatch
	(*IngestResponse)(nil),        // 2: astrawatch.agent.v1.IngestResponse
	(*HealthRequest)(nil),         // 3: astrawatch.agent.v1.HealthRequest
	(*HealthResponse)(nil),        // 4: astrawatch.agent.v1.HealthResponse
	(*AgentIdentity)(nil),         // 5: astrawatch.agent.v1.AgentIdentity
	nil,                           // 6: astrawatch.agent.v1.MetricPoint.LabelsEntry
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_internal_ingest_agentproto_agent_proto_depIdxs = []int32{
	7, // 0: astrawatch.agent.v1.MetricPoint.timestamp:type_name -> google.protobuf.Timestamp
	6, // 1: astrawatch.agent.v1.MetricPoint.labels:type_name -> astrawatch.agent.v1.MetricPoint.LabelsEntry
	0, // 2: astrawatch.agent.v1.MetricBatch.metrics:type_name -> astrawatch.agent.v1.MetricPoint
	1, // 3: astrawatch.agent.v1.AgentIngest.StreamMetrics:input_type -> astrawatch.agent.v1.MetricBatch
	1, // 4: astrawatch.agent.v1.AgentIngest.SendMetricBatch:input_type -> astrawatch.agent.v1.MetricBatch
	3, // 5: astrawatch.agent.v1.AgentIngest.HealthCheck:input_type -> astrawatch.agent.v1.HealthRequest
	2, // 6: astrawatch.agent.v1.AgentIngest.StreamMetrics:output_type -> astrawatch.agent.v1.IngestResponse
	2, // 7: astrawatch.agent.v1.AgentIngest.SendMetricBatch:output_type -> astrawatch.agent.v1.IngestResponse
	4, // 8: astrawatch.agent.v1.AgentIngest.HealthCheck:output_type -> astrawatch.agent.v1.HealthResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_internal_ingest_agentproto_agent_proto_init() }
func file_internal_ingest_agentproto_agent_proto_init() {
	if File_internal_ingest_agentproto_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_ingest_agentproto_agent_proto_rawDesc), len(file_internal_ingest_agentproto_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_ingest_agentproto_agent_proto_goTypes,
		DependencyIndexes: file_internal_ingest_agentproto_agent_proto_depIdxs,
		MessageInfos:      file_internal_ingest_agentproto_agent_proto_msgTypes,
	}.Build()
	File_internal_ingest_agentproto_agent_proto = out.File
	file_internal_ingest_agentproto_agent_proto_goTypes = nil
	file_internal_ingest_agentproto_agent_proto_depIdxs = nil
}
